import React from "react";
import type { Report } from "../../types/Report";

interface PrintableReportProps {
  report: Report;
}

const PrintableReport: React.FC<PrintableReportProps> = ({ report }) => {
  return (
    <div className="hidden print:block p-10 bg-white text-black min-h-screen" id="printable-area">
      {/* Header du Rapport */}
      <div className="flex justify-between items-start border-b-2 border-black pb-6 mb-8">
        <div>
          <h1 className="text-3xl font-black uppercase tracking-tighter">Incident Report</h1>
          <p className="text-sm font-mono text-gray-500">ID: {report.id}</p>
        </div>
        <div className="text-right">
          <p className="font-bold uppercase text-xs tracking-widest text-red-600">PSEVO Engine v26.0</p>
          <p className="text-sm">{new Date(report.createdAt).toLocaleString('fr-FR')}</p>
        </div>
      </div>

      {/* Section Verdict */}
      <div className="mb-10 p-6 border-4 border-black">
        <p className="text-xs font-bold uppercase tracking-[0.3em] mb-2">Final Classification</p>
        <h2 className="text-5xl font-black uppercase mb-2">{report.verdict.label}</h2>
        <p className="text-lg italic text-gray-700">{report.verdict.result === 'TIER_1' ? 'Major Event - Immediate Action Required' : 'Process Safety Incident'}</p>
      </div>

      {/* Infos Analyste */}
      <div className="grid grid-cols-3 gap-4 mb-10 bg-gray-100 p-4 font-mono text-xs">
        <div>
          <p className="font-bold text-gray-500 uppercase">Analyst</p>
          <p>{report.user.name}</p>
        </div>
        <div>
          <p className="font-bold text-gray-500 uppercase">Site / Version</p>
          <p>{report.user.site}</p>
        </div>
        <div>
          <p className="font-bold text-gray-500 uppercase">Duration</p>
          <p>{Math.floor(report.session.durationSeconds / 60)}m {report.session.durationSeconds % 60}s</p>
        </div>
      </div>

      {/* Table des réponses (Le chemin critique) */}
      <h3 className="text-sm font-bold uppercase tracking-widest mb-4 border-b border-gray-300 pb-2">Decision Path Log</h3>
      <table className="w-full text-left text-xs border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="py-2 px-1 w-16">Step</th>
            <th className="py-2 px-1">Question</th>
            <th className="py-2 px-1 w-20 text-right">Answer</th>
          </tr>
        </thead>
        <tbody>
          {report.answers.map((ans, idx) => (
            <tr key={idx} className="border-b border-gray-200">
              <td className="py-3 px-1 font-bold">{ans.validation}</td>
              <td className="py-3 px-1">{ans.questionTitle}</td>
              <td className={`py-3 px-1 text-right font-black ${ans.answer === 'OUI' ? 'text-red-600' : 'text-blue-600'}`}>
                {ans.answer}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Footer */}
      <div className="mt-20 pt-8 border-t border-gray-200 text-[10px] text-gray-400 text-center uppercase tracking-[0.2em]">
        Generated by PSEVO Classifier · Confidential Operational Document
      </div>
    </div>
  );
};

export default PrintableReport;